 create table if not exists users(
                      id int  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      email varchar,
                      login varchar,
                      name varchar,
                      birthday date
);
create table if not exists ratings(
                        rating_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        rating_name varchar
);
create table if not exists films(
                      id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      name varchar,
                      description varchar,
                      release_date date,
                      duration int,
                      rating_id int REFERENCES ratings (rating_id)
);
create table if not exists likes(
                      user_id int REFERENCES users (id),
                      film_like_id int REFERENCES films (id)

);
create table if not exists friends(
                        user_id int REFERENCES users (id),
                        friend_id int REFERENCES users (id)
);
create table if not exists genre(
                      genre_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      genre_name varchar
);
create table if not exists film_genre(
                           film_id int REFERENCES films (id),
                           genre_id int REFERENCES genre (genre_id)
);